#                                            Regularization in Logistic Regression


NAME = Mayank Chandra Joshi

Roll No. = CSC/20/31

University Roll No.= 20059570023

In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [2]:
data = pd.read_csv('student_data.csv')
numerical_columns = ['academic_performance', 'extracurricular_activities','time_management']
scaler = StandardScaler()
scaler.fit(data[numerical_columns])
data[numerical_columns] = scaler.transform(data[numerical_columns])
print(data)

     age gender  academic_performance  extracurricular_activities  \
0     24      M              0.520601                    1.266382
1     21      F              0.106988                   -0.514245
2     22      M              1.003149                   -0.514245
3     24      M              0.796343                   -1.226496
4     20      M             -1.202786                    0.198006
..   ...    ...                   ...                         ...
995   23      F              1.658036                    0.198006
996   18      F             -1.444060                    0.554131
997   24      M             -0.995980                    1.622507
998   21      M              1.658036                   -0.514245
999   23      F              0.624004                    0.198006

     time_management social_skills motivation  attendance communication  \
0           0.039716     Excellent        Low          48          Good
1          -1.353834          Poor       High          51     Very Good
2           0.039716          Poor        Low          28          Fair
3           0.039716          Good     Medium          20          Good
4          -1.353834     Very Good     Medium          89          Poor
..               ...           ...        ...         ...           ...
995         0.736491          Fair     Medium          95     Very Good
996        -1.353834     Excellent     Medium          61     Very Good
997         0.736491     Very Good     Medium          85          Poor
998        -1.353834     Excellent        Low          17          Poor
999        -1.353834     Very Good     Medium          45          Good

      teamwork  suitable     sender   subject  body_length  has_attachment  \
0         Good         1  colleague  discount         5356               0
1    Excellent         1     friend  discount         4077               0
2    Excellent         0     friend     offer         4898               0
3         Fair         0  colleague   meeting         1417               0
4         Fair         0  colleague     prize         8846               0
..         ...       ...        ...       ...          ...             ...
995       Poor         0  colleague     offer         9395               1
996  Excellent         1  colleague   meeting         2823               1
997  Very Good         0     friend   meeting         5287               1
998       Fair         0  colleague     offer         3285               1
999       Poor         1     friend  discount         7433               0

     is_reply  is_forward  is_spam
0           1           0        0
1           1           1        0
2           0           0        1
3           0           1        1
4           0           0        1
..        ...         ...      ...
995         1           0        1
996         1           0        1
997         1           0        1
998         1           1        1
999         1           0        1

[1000 rows x 18 columns]

In [3]:
data

,age,gender,academic_performance,extracurricular_activities,time_management,social_skills,motivation,attendance,communication,teamwork,suitable,sender,subject,body_length,has_attachment,is_reply,is_forward,is_spam
0,24,M,0.520601,1.266382,0.039716,Excellent,Low,48,Good,Good,1,colleague,discount,5356,0,1,0,0
1,21,F,0.106988,-0.514245,-1.353834,Poor,High,51,Very Good,Excellent,1,friend,discount,4077,0,1,1,0
2,22,M,1.003149,-0.514245,0.039716,Poor,Low,28,Fair,Excellent,0,friend,offer,4898,0,0,0,1
3,24,M,0.796343,-1.226496,0.039716,Good,Medium,20,Good,Fair,0,colleague,meeting,1417,0,0,1,1
4,20,M,-1.202786,0.198006,-1.353834,Very Good,Medium,89,Poor,Fair,0,colleague,prize,8846,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,23,F,1.658036,0.198006,0.736491,Fair,Medium,95,Very Good,Poor,0,colleague,offer,9395,1,1,0,1
996,18,F,-1.444060,0.554131,-1.353834,Excellent,Medium,61,Very Good,Excellent,1,colleague,meeting,2823,1,1,0,1
997,24,M,-0.995980,1.622507,0.736491,Very Good,Medium,85,Poor,Very Good,0,friend,meeting,5287,1,1,0,1
998,21,M,1.658036,-0.514245,-1.353834,Excellent,Low,17,Poor,Fair,0,colleague,offer,3285,1,1,1,1
999,23,F,0.624004,0.198006,-1.353834,Very Good,Medium,45,Good,Poor,1,friend,discount,7433,0,1,0,1